name: Build for Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: Checkout Git Repo
      uses: actions/checkout@v5

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          make
          diffutils
          coreutils
          grep
          gawk
          findutils
          python
          perl
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-zlib

    - name: Build
      shell: msys2 {0}
      run: |
        mingw32-make -j4 CC=gcc

    - name: Test
      shell: msys2 {0}
      run: |
        mingw32-make CC=gcc test

    - name: Upload zip
      uses: actions/upload-artifact@v4
      with:
          name: luna-win64
          path: "luna.exe"
          if-no-files-found: error
